version: '3.8'

services:
  web:
    build: .
    image: django-todolist:1.0.0  # Семантичне версіонування
    ports:
      - "8000:8000"
    environment:
      - ENGINE=${ENGINE:-django.db.backends.sqlite3}
      - NAME=${NAME:-db.sqlite3}
      - USER=${USER:-}
      - PASSWORD=${PASSWORD:-}
      - HOST=${HOST:-}
      - PORT=${PORT:-}
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${NAME:-todolist}
      - POSTGRES_USER=${USER:-postgres}
      - POSTGRES_PASSWORD=${PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: